### ISSUE TITLE
frontend oldal dizájnja

### ISSUE THREAD

**Issue by pisipite** [Code-for-Hungary/bmm-frontend#2]
amire szükség van:
- frontend oldal dizájnja: Egy darab statikus html minimális javascripttel. Teszt oldal: http://bmmfrontend.billy.hu/
- logó

tartalom itt gyűlik: https://docs.google.com/document/d/1olysonMb8gLbCj94Aha5dP1iejIVrF6p2woECyzio4A/edit?disco=AAAA1BfGK6s&usp_dm=true

nem kell nagyon csicsa, valami egyszerű, letisztult lenne a legjobb. színvilág lehetne a k-kék (#0363A0) és fehér.

**Comment by Klosmi** [comment]
Okay, pénteken neki látok 🏄.
Szóval design + az implementáció (azaz html, js) amire szükség van? 
Logónak a _BMM_ tipografikus megközelítésére gondoltam.

**Comment by Klosmi** [comment]
👍
